name: Restore cuttools/iregi cache
description: Restores lhapdf from cache and sets MG5 accordingly

runs:
  using: composite
  steps:
    - name: Set cache key
      run: echo "CACHE_KEY=NLO-$ImageOS" >> $GITHUB_ENV
      shell: bash

    - uses: actions/cache/restore@v4
      with:
        path: ~/.cache/HEPtools
        key: ${{ env.CACHE_KEY }}

    - uses: actions/cache/restore@v4
      with:
        path: ~/.cache/UFOMODEL
        key: ufomodel

    - run: |
        cd $GITHUB_WORKSPACE
        rm -rf /home/runner/.cache/HEPtools/IREGI
        rm -rf  /home/runner/.cache/HEPtools/CutTools
        echo "PYTHONPATH=$PYTHONPATH:$HOME/.cache/UFOMODEL" >> $GITHUB_ENV
        cp -r $HOME/.cache/UFOMODEL/* $GITHUB_WORKSPACE/models
        ls $GITHUB_WORKSPACE/models
        echo "heptools_install_dir=/home/runner/.cache/HEPtools" >> input/mg5_configuration.txt
        echo "lhapdf = /home/runner/.cache/HEPtools/bin/lhapdf-config" >>       input/mg5_configuration.txt
        echo "lhapdf_py3 = /home/runner/.cache/HEPtools/bin/lhapdf-config" >>       input/mg5_configuration.txt
        echo "pythia8_path = /home/runner/.cache/HEPtools/pythia8" >>  input/mg5_configuration.txt
        echo "hepmc_path = /home/runner/.cache/HEPtools/hepmc" >>  input/mg5_configuration.txt
        echo " mg5amc_py8_interface_path = /home/runner/.cache/HEPtools/MG5aMC_PY8_interface" >>  input/mg5_configuration.txt
        echo "ninja = /home/runner/.cache/HEPtools/ninja/lib" >>  input/mg5_configuration.txt
        echo "collier = /home/runner/.cache/HEPtools/collier" >>  input/mg5_configuration.txt
        echo "hepmc_path = /home/runner/.cache/HEPtools/hepmc" >>  input/mg5_configuration.txt
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/runner/.cache/HEPtools/lhapdf6_py3//lib:/home/runner/.cache/HEPtools/lib" >> $GITHUB_ENV
      shell: bash
