C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE FFV2_3(F1, F2, COUP, M3, W3,V3)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      REAL*8 M3
      REAL*8 OM3
      REAL*8 P3(0:3)
      COMPLEX*16 TMP1
      TYPE(ALOHA) V3
      REAL*8 W3
      COMPLEX*16 DENOM
      OM3 = 0D0
      IF (M3.NE.0D0) OM3=1D0/M3**2
      V3%P(:) = +F1%P(:)+F2%P(:)
      P3(:) = -V3 % P (:)
      FLV_INDEX1 = F1 %FLV_INDEX
      FLV_INDEX2 = F2 %FLV_INDEX
      IF(FLV_INDEX1.NE.FLV_INDEX2.OR.FLV_INDEX1.EQ.0D0)THEN
        V3%W(:) = (0D0,0D0)
        RETURN
      ENDIF
      TMP1 = (F1 % W(1)*(F2 % W(3)*(P3(0)+P3(3))+F2 % W(4)*(P3(1)+CI
     $ *(P3(2))))+F1 % W(2)*(F2 % W(3)*(P3(1)-CI*(P3(2)))+F2 % W(4)
     $ *(P3(0)-P3(3))))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      V3%W(1)= DENOM*(-CI)*(F2 % W(3)*F1 % W(1)+F2 % W(4)*F1 % W(2)
     $ -P3(0)*OM3*TMP1)
      V3%W(2)= DENOM*(-CI)*(-F2 % W(4)*F1 % W(1)-F2 % W(3)*F1 % W(2)
     $ -P3(1)*OM3*TMP1)
      V3%W(3)= DENOM*(-CI)*(-CI*(F2 % W(4)*F1 % W(1))+CI*(F2 % W(3)*F1
     $  % W(2))-P3(2)*OM3*TMP1)
      V3%W(4)= DENOM*(-CI)*(-F2 % W(3)*F1 % W(1)-P3(3)*OM3*TMP1+F2 %
     $  W(4)*F1 % W(2))
      END


