C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(1,2)
C     
      SUBROUTINE MP_R2_QQ_2_0(F1, F2, COUP,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      COMPLEX*32 TMP15
      COMPLEX*32 VERTEX
      FLV_INDEX1 = F1 %FLV_INDEX
      FLV_INDEX2 = F2 %FLV_INDEX
      IF(FLV_INDEX1.NE.FLV_INDEX2.OR.FLV_INDEX1.EQ.0D0)THEN
        VERTEX = (0D0,0D0)
        RETURN
      ENDIF
      TMP15 = (F2 % W(1)*F1 % W(1)+F2 % W(2)*F1 % W(2)+F2 % W(3)*F1 %
     $  W(3)+F2 % W(4)*F1 % W(4))
      VERTEX = COUP*(-CI * TMP15)
      END


