C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(-1,1)*Gamma(-1,2,1)) + Coup(2) * (Identity(1,2))
C     
      SUBROUTINE MP_R2_QQ_1_R2_QQ_2_0(F1, F2, COUP1, COUP2,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP1
      COMPLEX*32 COUP2
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      REAL*16 P1(0:3)
      COMPLEX*32 TMP15
      COMPLEX*32 TMP16
      COMPLEX*32 VERTEX
      P1(:) = F1 % P (:)
      FLV_INDEX1 = F1 %FLV_INDEX
      FLV_INDEX2 = F2 %FLV_INDEX
      IF(FLV_INDEX1.NE.FLV_INDEX2.OR.FLV_INDEX1.EQ.0D0)THEN
        VERTEX = (0D0,0D0)
        RETURN
      ENDIF
      TMP15 = (F2 % W(1)*F1 % W(1)+F2 % W(2)*F1 % W(2)+F2 % W(3)*F1 %
     $  W(3)+F2 % W(4)*F1 % W(4))
      TMP16 = (F1 % W(1)*(F2 % W(3)*(P1(0)+P1(3))+F2 % W(4)*(P1(1)+CI
     $ *(P1(2))))+(F1 % W(2)*(F2 % W(3)*(P1(1)-CI*(P1(2)))+F2 % W(4)
     $ *(P1(0)-P1(3)))+(F1 % W(3)*(F2 % W(1)*(P1(0)-P1(3))-F2 % W(2)
     $ *(P1(1)+CI*(P1(2))))+F1 % W(4)*(F2 % W(1)*(-P1(1)+CI*(P1(2)))
     $ +F2 % W(2)*(P1(0)+P1(3))))))
      VERTEX = (-1Q0)*(+CI*(COUP1*TMP16+TMP15*COUP2))
      END


