C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,4)*Metric(2,3) - Metric(1,2)*Metric(3,4)
C     
      SUBROUTINE VVVV3P0_1(V2, V3, V4, COUP, M1, W1,V1)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M1
      REAL*8 P1(0:3)
      COMPLEX*16 TMP2
      COMPLEX*16 TMP8
      TYPE(ALOHA) V1
      TYPE(ALOHA) V2
      TYPE(ALOHA) V3
      TYPE(ALOHA) V4
      REAL*8 W1
      COMPLEX*16 DENOM
      V1%P(:) = +V2%P(:)+V3%P(:)+V4%P(:)
      P1(:) = -V1 % P (:)
      TMP2 = (V3 % W(1)*V4 % W(1)-V3 % W(2)*V4 % W(2)-V3 % W(3)*V4 %
     $  W(3)-V3 % W(4)*V4 % W(4))
      TMP8 = (V2 % W(1)*V3 % W(1)-V2 % W(2)*V3 % W(2)-V2 % W(3)*V3 %
     $  W(3)-V2 % W(4)*V3 % W(4))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      V1%W(1)= DENOM*(-CI*(V4 % W(1)*TMP8)+CI*(V2 % W(1)*TMP2))
      V1%W(2)= DENOM*(-CI*(V4 % W(2)*TMP8)+CI*(V2 % W(2)*TMP2))
      V1%W(3)= DENOM*(-CI*(V4 % W(3)*TMP8)+CI*(V2 % W(3)*TMP2))
      V1%W(4)= DENOM*(-CI*(V4 % W(4)*TMP8)+CI*(V2 % W(4)*TMP2))
      END


